version: '3.8'

services:
  rabbitmq:
    image: "rabbitmq:management"
    container_name: rabbitmq
    ports:
      - "5672:5672"    # RabbitMQ AMQP protocol port
      - "15672:15672"  # RabbitMQ management UI port
    networks:
      - test
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:8.17.2"
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - test
    volumes:
      - es_data:/usr/share/elasticsearch/data

  tcp-producer-service:
    build:
      context: .
      dockerfile: Dockerfile  # Ensure to provide your Dockerfile to build the image for your service
    container_name: tcp-producer-service
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
    depends_on:
      - rabbitmq
    networks:
      - test
      
  tcp-consumer-service:
    build:
      context: .
      dockerfile: Dockerfile  # Ensure to provide your Dockerfile to build the image for your service
    container_name: tcp-consumer-service
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ELASTICSEARCH_HOST: elasticsearch
    depends_on:
      - rabbitmq
      - elasticsearch
    networks:
      - test

volumes:
  es_data:
    driver: local

networks:
  my_network:
    driver: bridge
